apiVersion: v2
name: elk
description: ELK stack for logging
type: application
version: 0.1.0

dependencies:
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
  - name: logstash
    version: 8.5.1
    repository: https://helm.elastic.co
  - name: kibana
    version: 8.5.1
    repository: https://helm.elastic.co
