spring:
  application:
    name: cash-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
      client:
        registration:
          cash-service:
            client-id: cash-service
            client-secret: s1
            authorization-grant-type: client_credentials
            scope: accounts.write
        provider:
          auth-server:
            token-uri: http://auth-server:9000/oauth2/token
