spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**
        - id: cash-service.yml
          uri: lb://cash-service.yml
          predicates:
            - Path=/api/cash/**
        - id: transfer-service
          uri: lb://transfer-service
          predicates:
            - Path=/api/transfers/**
      discovery:
        locator:
          enabled: true

server:
  port: 8085