spring:
  application:
    name: notifications-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

resilience4j:
  circuitbreaker:
    instances:
      notify:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s