spring:
  application:
    name: transfer-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
      client:
        registration:
          transfer-service:
            client-id: transfer-service
            client-secret: s2
            authorization-grant-type: client_credentials
            scope: accounts.write
        provider:
          auth-server:
            token-uri: http://localhost:9000/oauth2/token

resilience4j:
  circuitbreaker:
    instances:
      transfer:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
  retry:
    instances:
      transfer:
        max-attempts: 3
        wait-duration: 200ms
